version: '3'
services:
  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    volumes:
      - './frontend-angular:/app'
    ports:
      - '4200:4200'
  backend:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    volumes:
      - './backend-nodejs:/app'
      - '${HOME}/.aws:/root/.aws'
    ports:
      - '3000:3000'
    environment:
      - COGNITO_REGION=${COGNITO_REGION}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - COGNITO_JWKS=${COGNITO_JWKS}
      - CORBADO_PROJECT_ID=${CORBADO_PROJECT_ID}
      - CORBADO_API_SECRET=${CORBADO_API_SECRET}
      - CORBADO_CLI_SECRET=${CORBADO_CLI_SECRET}
      - CORBADO_WEBHOOK_USERNAME=${CORBADO_WEBHOOK_USERNAME}
      - CORBADO_WEBHOOK_PASSWORD=${CORBADO_WEBHOOK_PASSWORD}